KNOWN_TESTS = [
    'FBS', 'PPBS', 'BLOOD UREA', 'S.CREATINE', 'CHOLESTEROL (TOTAL)', 'HDL CHOLESTEROL',
    'S.TRIGLYCERIDE', 'CALCIUM', 'URIC ACID', 'PHOSPHOROUS', 'S. BILIRUBIN', 'BICARBONATE',
    'GGTP', 'SGPT', 'SGOT', 'HBSAG', 'BONE MARROW', 'HIV', 'SP.AFB', 'CBC', 'HB.', 'URINE',
    'ESR', 'COOMBS TEST', 'CPK - MB', 'LDH', 'CSF ROUTINE', 'URINE PREGNANCY TEST', 'G6PD',
    'BLOOD GROUP RH', 'PL. FLUID', 'RA WITH TITER', 'PTTK', 'RETIC COUNT', 'AEC', 'STOOL',
    'S.WIDAL', 'PLATELET COUNT', 'S AMYLASE', 'ASO TITERS', 'CRP', 'URINE PROTIEN 24 HOUR',
    'RBC INDICES', 'TCDC', 'PSMP', 'PSCM', 'PCV (Hematocrete)', 'S. PROTEIN', 'PSA', 'VDRL',
    'ALKPO4', 'S Sodium ([NA+)', 'MT TEST', 'BLOOD CULTURE', 'RBS', 'BT, CT.', 'CPK',
    'S.POTTASIUM (K+)', 'URINE CULTURE', 'TSH', 'SCIKLING TEST', 'S. Chloride (Cl-)',
    'PLASMA TESTOSTERONE', 'ASCTIES FLUID', 'GLYCOSYLATED HB (HbA1c)', 'SYPHILIS DIPSTICK',
    'LIPASE TEST', 'SERUM INSULIN', 'HB.ELECTROPHORESIS', 'S.LITHIUM', 'PROTHROMBIN TIME',
    'S.ACETONE', 'LE CELL TEST', 'ACID PHOSPHATASE', 'S.FERRITIN', 'TwentyFour Hr Urinary Calcium',
    'Lp (a)', 'C.E.A.', 'Homocysteine', 'HIV (ELISA)', 'F.N.A.C.', 'A.N.A.', 'Plasma Cortisol',
    'Pleural Fluid', 'Serum B12', 'Biopsy Histopathology', 'Urine Amino Acid',
    'S Valproic Acid level', 'ADA', 'Serum HCG titer', 'Free T3', 'Free T4', 'AntiHCV Antibody',
    'FSH', 'LH', 'Urine Microalbumin', 'Troponin T', 'S. Prolactin', 'Serum Protein Electrophoresis',
    'Urinary Potassium', 'HCV', 'Vitamin D3', 'T3', 'T4', 'Dengue IgG', 'Dengue IgM', 'Dengue NS1',
    'LDL Cholesterol', 'VLDL Cholesterol', 'S.Chloride', 'AFP', 'HCG', 'Average Sugar',
    'S. Globulin', 'Direct Bilirubin', 'Indirect Bilirubin', 'S. Widal O', 'S. Widal H',
    'S. Widal A', 'S. Widal B', 'TB IgM', 'TB IgG', 'T3,T4,TSH', 'CA 125', 'Chikungunya IgM',
    'Serum Vitamin D level', 'Dengue NS1&IgM&IgG', 'HBeAg', 'Alfa Feto Protein', 'S.Magnesium',
    'Ca. 19.9', 'Anti TPO Antibodies', 'UACR (Urinary Albumin Creat Ratio)'
]